scratch-org-def: config/project-scratch-def.json
assign-permset: true
permset-name: Aura_Perfs
run-apex-tests: false
delete-scratch-org: false
show-scratch-org-url: true
open-path: /lightning/n/Iteration